language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 12.3
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake assets:precompile
deploy:
  provider: heroku
  api_key:
    secure: KEY
  app: be-saturnd-earth
  on:
    repo: Saturnd-Earth/se-be
    branch: main
  skip_cleanup: 'true'
  run: rails db:migrate
